_target_: experiments.amplitudes.wrappers.AmplitudeCLSTrWrapper

net:
  _target_: experiments.baselines.CLSTr

  in_channels: 8
  out_channels: 1
  hidden_channels: 128

  num_sa_blocks: 2
  num_ca_blocks: 2
  num_heads: 4

  pos_encoding: false
