_target_: experiments.amplitudes.wrappers.AmplitudeDSMLPWrapper

net:
  _target_: experiments.baselines.ds_mlp.DSMLP

  in_shape: 20
  out_shape: 1
  
  num_particles_boson: 1
  num_particles_glu: 3
  
  hidden_channels_prenet: 384
  hidden_layers_prenet: 2
  out_dim_prenet_sep: 32
  hidden_channels_net: 384
  hidden_layers_net: 2
