_target_: experiments.toptagging.wrappers.TopTaggingGATrWrapper

net:
 _target_: gatr.nets.GATr

 in_mv_channels: 1
 out_mv_channels: 1
 hidden_mv_channels: 8

 in_s_channels: 1
 out_s_channels: 1
 hidden_s_channels: 16

 num_blocks: 8
 reinsert_mv_channels: null
 reinsert_s_channels: null
 dropout_prob: null

 attention:
  num_heads: 8
  multi_query: false
  increase_hidden_channels: 2

defaults:
 - /base_attention@net.attention
 - /base_mlp@net.mlp