_target_: experiments.amplitudes.wrappers.AmplitudeGATrWrapper

net:
 _target_: gatr.nets.GATr

 in_mv_channels: 1
 out_mv_channels: 1
 hidden_mv_channels: 4

 in_s_channels: 4
 out_s_channels: 1
 hidden_s_channels: 16

 num_blocks: 4
 reinsert_mv_channels: null
 reinsert_s_channels: null
 dropout_prob: null

defaults:
 - /base_attention@net.attention
 - /base_mlp@net.mlp