_target_: experiments.toptagging.wrappers.TopTaggingGATrWrapper
force_xformers: '${training.force_xformers}'
beam_reference: null

net:
 _target_: gatr.nets.GATr

 in_mv_channels: 1
 out_mv_channels: 1
 hidden_mv_channels: 8

 in_s_channels: 1
 out_s_channels: 1
 hidden_s_channels: 8

 num_blocks: 4
 reinsert_mv_channels: null
 reinsert_s_channels: null
 dropout_prob: null

 attention:
  num_heads: 4
  multi_query: false
  increase_hidden_channels: 2

defaults:
 - /base_attention@net.attention
 - /base_mlp@net.mlp
