_target_: experiments.amplitudes.wrappers.AmplitudeGATrWrapper
reinsert_type_token: false

net:
 _target_: gatr.nets.GATr

 in_mv_channels: 1
 out_mv_channels: 1
 hidden_mv_channels: 4

 in_s_channels: 4
 out_s_channels: 1
 hidden_s_channels: 32

 num_blocks: 8
 reinsert_mv_channels: null
 reinsert_s_channels: null
 dropout_prob: null
 double_layernorm: false

 attention:
  num_heads: 8
  multi_query: false
  increase_hidden_channels: 2
  head_scale: false

defaults:
 - /base_attention@net.attention
 - /base_mlp@net.mlp
