_target_: experiments.eventgen.afterburner.Nuke
beam_reference: spacelike
two_beams: false
add_time_reference: true

net:
 _target_: gatr.nets.GATr

 in_mv_channels: 1
 out_mv_channels: 1
 hidden_mv_channels: 4

 in_s_channels: null
 out_s_channels: 1
 hidden_s_channels: 8

 num_blocks: 1
 reinsert_mv_channels: null
 reinsert_s_channels: null
 dropout_prob: null

 attention:
  num_heads: 2
  multi_query: false
  increase_hidden_channels: 2

afterburner:
 _target_: experiments.baselines.MLP

 in_shape: 16
 out_shape: 2
 hidden_channels: 64
 hidden_layers: 2

defaults:
 - /base_attention@net.attention
 - /base_mlp@net.mlp
