exp_name: ???
exp_type: ???
run_name: null
base_dir: .

jobid: null
seed: null
debug: false

warm_start_idx: null
save: true
use_mlflow: true
save_source: true
ema: false

ga_settings:
 use_fully_connected_subgroup: true
 use_geometric_product: true
 mix_mvpseudoscalar_into_scalar: true
 zero_bivector: false

train: true
training:
 iterations : 20
 train_test_val: [.4, .5, .1]
 subsample: null
 es_patience: 100
 es_load_best_model: true
 validate_every_n_steps: 100

 clip_grad_norm: 5
 clip_grad_value: null
 max_grad_norm: null
 log_every_n_steps: 1000

 optimizer : Adam
 lr: 3.e-4
 batchsize: 256
 betas: [.9, .999]
 eps: 1.e-8
 weight_decay: 0
 
 scheduler: null
 scheduler_scale: 1
 cosanneal_eta_min: 0
 reduceplateau_factor: 0.1
 reduceplateau_patience: 50
 onecycle_max_lr: 10
 onecycle_pct_start: 0.3

 ema_decay: 0.99

 dtype: float32
 enable_flash_sdp: false
 enable_math_sdp: true
 enable_mem_efficient_sdp: false
 force_xformers: false

evaluate: true
evaluation:
 batchsize: 1024

plot: true
plotting:
 loss: true

mlflow:
 db: '${base_dir}/runs/${exp_name}/mlflow/mlflow.db'
 artifacts: '${base_dir}/runs/${exp_name}/mlflow/artifacts'

defaults:
 - hydra
 - _self_
