exp_type: ttbar
exp_name: ttbar

data:
 n_jets: [0]
 data_path_0j: data/ttbar_0j.npy
 data_path_1j: data/ttbar_1j.npy
 data_path_2j: data/ttbar_2j.npy
 data_path_3j: data/ttbar_3j.npy
 data_path_4j: data/ttbar_4j.npy
 subsample: null
 train_test_val: [.5, .4, .01]
 base_type: 2
 use_delta_r_min: true
 use_pt_min: true

odeint:
 method: rk4
 rtol: 1e-5
 atol: 1e-5
 options:
  step_size: 0.02

cfm:
 embed_t_dim: 8
 embed_t_scale: 30.
 hutchinson: true
 coordinates: StandardLogPtPhiEtaLogM2
 geometry:
  type: simple
  periodic: true
 transforms_float64: true

gpt:
 channels: [1,0,2,3,5,4,6,7,9,8,10,11,13,12,14,15,17,16,18,19,21,20,22,23,25,24,26,27,29,28,30,31,33,32,34,35,37,36,38,39]
 transforms_float64: true

training:
 iterations: 200000
 batchsize: 2048
 scheduler: ReduceLROnPlateau
 es_patience: 50
 validate_every_n_steps: 1000
 log_every_n_steps: 1000
 lr: 1e-3
 reduceplateau_patience: 20

evaluation:
 sample: true
 save_samples: false
 nsamples: 1000000
 batchsize: 4096
 eval_loss: []
 eval_log_prob: [val] # expensive
 classifier: true

plot: true
plotting:
 loss: true
 fourmomenta: true
 jetmomenta: true
 preprocessed: true
 virtual: true
 delta: true
 deta_dphi: true
 log_prob: true
 reweighted: true
 create_mask: false

defaults:
- model: gatr_eventgen
- classifier: classifier
- default
