### General ###
runs_dir : /media/jspinner/shared/Studium/project3/lorentz-gatr/runs
run_name : amplitudes_mlp_
redirect_console : False
experiment_type : "amplitudes"
model : mlp

dataset : "zjj"
data_path : /media/jspinner/shared/Studium/project3/data/

n_epochs : 5
data_split : .5