exp_type: binaryjetclass
exp_name: jc_local_debug

data:
 data_dir: data/jetclass/
 features: fourmomenta
 train_files_range: [122,123]
 test_files_range: [123,124]
 val_files_range: [124,125]

jc_params:
 num_workers: 4
 fetch_step: 0.01
 extra_selection: null
 extra-test-selection: null
 fetch_by_files: False
 in_memory: False
 not_remake_weights: False
 steps_per_epoch: null
 steps_per_epoch_val: null

defaults:
 - default_tagging
