exp_type: jctagging
exp_name: jc_local_debug

data:
 data_dir: data/jetclass/
 score_token: false
 features: default

jc_params:
 num_workers: 1
 fetch_step: 0.01
 extra_selection: null
 extra-test-selection: null
 data_fraction: 1.0
 file_fraction: 1.0
 fetch_by_files: False
 in_memory: False
 not_remake_weights: False
 steps_per_epoch: null
 steps_per_epoch_val: null
 samples_per_epoch: null
 samples_per_epoch_val: null
 local_rank: null
 copy_inputs: False
 num_classes: 10

plotting:
 roc: false
 score: false

defaults:
 - default_tagging
