exp_type: jctagging
exp_name: jc_local_debug

data:
 data_dir: data/jetclass/
 score_token: false
 features: default
 train_files_range: [0,100]
 test_files_range: [100,120]
 val_files_range: [120,125]

jc_params:
 num_workers: 4
 fetch_step: 0.01
 extra_selection: null
 extra-test-selection: null
 fetch_by_files: False
 in_memory: False
 not_remake_weights: False
 steps_per_epoch: null
 steps_per_epoch_val: null

plotting:
 roc: false
 score: false

defaults:
 - default_tagging
