exp_type: qgtagging
exp_name: qgtag_local_debug
base_dir: /remote/gpu02/breso/lorentz-gatr

data:
 data_dir : /remote/gpu02/breso/lorentz-gatr/data
 dataset: qg_data
 pairs:
  use: false
  add_differences: true
  directed: true
  top_k: 10
  lowest_kt: false
  add_scalars: true
 beam_reference: null
 add_time_reference: false
 add_pt: false
 add_jet_momentum: false
 reinsert_channels: false
 rescale_data: true

train: true
training:
 iterations: 10
 batchsize: 128
 lr: 1e-3

 force_xformers: true

evaluation:
 batchsize: 128
 save_roc: false

plotting:
 roc: true
 loss: true
 score: true

sweep: # only used for sweeps
 seed: null
 trials: 10
 optuna_db: '${base_dir}/runs/${exp_name}/optuna/optuna.db'

defaults:
 - model: gatr_qgtagging
 - default
 - hydra
 - _self_
