_target_: experiments.eventgen.dnet.DisplacementTransformer
net:
 _target_: experiments.baselines.transformer.Transformer
 _partial_: true
 
 in_channels: null
 out_channels: 4
 hidden_channels: 32
 
 num_blocks: 1
 num_heads: 2
