_target_: experiments.eventgen.wrappers.GAPCFM
beam_reference: spacelike
two_beams: false
add_time_reference: true
scalar_dims: [0, 3]

net:
 _target_: gatr.nets.GAP

 in_mv_channels: null
 out_mv_channels: null
 hidden_mv_channels: 16

 in_s_channels: 1
 out_s_channels: 4
 hidden_s_channels: 32

 num_blocks: 12
 dropout_prob: null

defaults:
 - /base_mlp@net.mlp