_target_: experiments.amplitudes.wrappers.AmplitudeGAPWrapper

net:
 _target_: gatr.nets.GAP

 in_mv_channels: 4
 out_mv_channels: 1
 hidden_mv_channels: 96

 in_s_channels: 1
 out_s_channels: null
 hidden_s_channels: 96

 num_blocks: 8
 dropout_prob: null
 num_layers: 2

defaults:
 - /base_mlp@net.mlp
