_target_: experiments.eventgen.wrappers.TransformerCFM

net:
 _target_: experiments.baselines.Transformer

 in_channels: null
 out_channels: 4
 hidden_channels: 108

 num_blocks: 6
 num_heads: 8
 dropout_prob: null

 pos_encoding: false