data_config: /remote/gpu02/breso/lorentz-gatr-pretrain/data/data_config.yaml

num_workers: 1
fetch_step: 0.01
extra_selection: null
extra-test-selection: null
data_fraction: 1.0
file_fraction: 1.0
fetch_by_files: False
in_memory: False
not_remake_weights: False
steps_per_epoch: null
steps_per_epoch_val: null
samples_per_epoch: null
samples_per_epoch_val: null
local_rank: null
copy_inputs: False

data_train: ["HToBB:/remote/gpu02/breso/lorentz-gatr-pretrain/data/JetClass/Pythia/train_100M/HToBB_*.root", "HToCC:/remote/gpu02/breso/lorentz-gatr-pretrain/data/JetClass/Pythia/train_100M/HToCC_*.root", "HToGG:/remote/gpu02/breso/lorentz-gatr-pretrain/data/JetClass/Pythia/train_100M/HToGG_*.root", "HToWW2Q1L:/remote/gpu02/breso/lorentz-gatr-pretrain/data/JetClass/Pythia/train_100M/HToWW2Q1L_*.root", "HToWW4Q:/remote/gpu02/breso/lorentz-gatr-pretrain/data/JetClass/Pythia/train_100M/HToWW4Q_*.root", "TTBar:/remote/gpu02/breso/lorentz-gatr-pretrain/data/JetClass/Pythia/train_100M/TTBar_*.root", "TTBarLep:/remote/gpu02/breso/lorentz-gatr-pretrain/data/JetClass/Pythia/train_100M/TTBarLep_*.root", "WToQQ:/remote/gpu02/breso/lorentz-gatr-pretrain/data/JetClass/Pythia/train_100M/WToQQ_*.root", "ZToQQ:/remote/gpu02/breso/lorentz-gatr-pretrain/data/JetClass/Pythia/train_100M/ZToQQ_*.root", "ZJetsToNuNu:/remote/gpu02/breso/lorentz-gatr-pretrain/data/JetClass/Pythia/train_100M/ZJetsToNuNu_*.root"]

data_val: ["/remote/gpu02/breso/lorentz-gatr-pretrain/data/JetClass/Pythia/val_5M/*.root"]

data_test: ["HToBB:/remote/gpu02/breso/lorentz-gatr-pretrain/data/JetClass/Pythia/test_20M/HToBB_*.root", "HToCC:/remote/gpu02/breso/lorentz-gatr-pretrain/data/JetClass/Pythia/test_20M/HToCC_*.root", "HToGG:/remote/gpu02/breso/lorentz-gatr-pretrain/data/JetClass/Pythia/test_20M/HToGG_*.root", "HToWW2Q1L:/remote/gpu02/breso/lorentz-gatr-pretrain/data/JetClass/Pythia/test_20M/HToWW2Q1L_*.root", "HToWW4Q:/remote/gpu02/breso/lorentz-gatr-pretrain/data/JetClass/Pythia/test_20M/HToWW4Q_*.root", "TTBar:/remote/gpu02/breso/lorentz-gatr-pretrain/data/JetClass/Pythia/test_20M/TTBar_*.root", "TTBarLep:/remote/gpu02/breso/lorentz-gatr-pretrain/data/JetClass/Pythia/test_20M/TTBarLep_*.root", "WToQQ:/remote/gpu02/breso/lorentz-gatr-pretrain/data/JetClass/Pythia/test_20M/WToQQ_*.root", "ZToQQ:/remote/gpu02/breso/lorentz-gatr-pretrain/data/JetClass/Pythia/test_20M/ZToQQ_*.root", "ZJetsToNuNu:/remote/gpu02/breso/lorentz-gatr-pretrain/data/JetClass/Pythia/test_20M/ZJetsToNuNu_*.root"]
